DROP TABLE IF EXISTS assignment CASCADE;
DROP TABLE IF EXISTS ship CASCADE;
DROP TABLE IF EXISTS rank CASCADE;
DROP TABLE IF EXISTS sailor CASCADE;
DROP TABLE IF EXISTS fleet CASCADE;

CREATE TABLE fleet (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE sailor (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  date_of_birth VARCHAR(10) NOT NULL
);

CREATE TABLE rank (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL
);

CREATE TABLE ship (
  id SERIAL PRIMARY KEY NOT NULL,
  fleet_id INTEGER NOT NULL REFERENCES fleet(id) ON DELETE CASCADE,
  name VARCHAR(50) NOT NULL,
  date_built VARCHAR(10) NOT NULL
);

CREATE TABLE assignment (
  id SERIAL PRIMARY KEY NOT NULL,
  rank_id INTEGER NOT NULL REFERENCES rank(id) ON DELETE CASCADE,
  ship_id INTEGER NOT NULL REFERENCES ship(id) ON DELETE CASCADE,
  sailor_id INTEGER NOT NULL REFERENCES sailor(id) ON DELETE CASCADE,
  start_date VARCHAR(10) NOT NULL,
  end_date VARCHAR(10) NOT NULL,
  name VARCHAR(50) NOT NULL
);